CREATE TABLE IF NOT EXISTS projects (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  github_id INT UNSIGNED NOT NULL DEFAULT 0,
  name VARCHAR(191) NOT NULL,
  full_name VARCHAR(191) NOT NULL,
  html_url VARCHAR(255) NOT NULL,
  description TEXT,
  stars INT UNSIGNED NOT NULL DEFAULT 0,
  forks INT UNSIGNED NOT NULL DEFAULT 0,
  language VARCHAR(64) NOT NULL DEFAULT '',
  topics TEXT,
  pushed_at DATETIME DEFAULT NULL,
  discovered_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_full_name (full_name),
  KEY idx_stars (stars),
  KEY idx_language (language),
  KEY idx_discovered_at (discovered_at)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS project_reports (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  project_id INT UNSIGNED NOT NULL,
  run_id INT UNSIGNED DEFAULT NULL,
  period_type VARCHAR(16) NOT NULL DEFAULT 'daily',
  report_date DATE NOT NULL,
  one_sentence VARCHAR(255) NOT NULL DEFAULT '',
  project_type VARCHAR(64) NOT NULL DEFAULT '',
  problem_text TEXT,
  tech_stack TEXT,
  target_users TEXT,
  play_score TINYINT UNSIGNED NOT NULL DEFAULT 0,
  useful_score TINYINT UNSIGNED NOT NULL DEFAULT 0,
  php_fit_score TINYINT UNSIGNED NOT NULL DEFAULT 0,
  difficulty VARCHAR(16) NOT NULL DEFAULT '',
  is_suitable_for_this_host TINYINT UNSIGNED NOT NULL DEFAULT 0,
  ideas_to_reuse TEXT,
  risks TEXT,
  recommendation VARCHAR(32) NOT NULL DEFAULT '',
  summary_zh TEXT,
  raw_ai_json MEDIUMTEXT,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_project_period (project_id, period_type, report_date),
  KEY idx_report_date (report_date),
  KEY idx_scores (php_fit_score, useful_score, play_score),
  KEY idx_recommendation (recommendation)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS runs (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  run_type VARCHAR(16) NOT NULL DEFAULT 'daily',
  status VARCHAR(16) NOT NULL DEFAULT 'started',
  started_at DATETIME NOT NULL,
  finished_at DATETIME DEFAULT NULL,
  total_found INT UNSIGNED NOT NULL DEFAULT 0,
  total_analyzed INT UNSIGNED NOT NULL DEFAULT 0,
  error_message TEXT,
  source VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY idx_run_type (run_type),
  KEY idx_status (status),
  KEY idx_started_at (started_at)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
